In [1]:
import numpy as np

In [9]:
a=np.arange(10)# 1D array

In [6]:
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
type(a)

numpy.ndarray

In [ ]:
2D Array

In [12]:
b=np.arange(12).reshape(4,3) # 4*3=12 

In [13]:
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [14]:
b=np.arange(12).reshape(5,2)# reshape numbers always match arane number

ValueError: cannot reshape array of size 12 into shape (5,2)

In [ ]:
3D Array

In [22]:
c=np.arange(24).reshape(2,3,4)# 3D

In [23]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
# Introduction to statistical concepts:

In [34]:
test_scores=np.array([32.32,56.98,21.52,44.32,55.63,13.75,43.47,43.34])

In [35]:
print('Mean test scores are given below calculated:')
print(np.mean(test_scores))

Mean test scores are given below calculated:
38.91625


In [36]:
print('Median test scores are given below calculated:')
print(np.median(test_scores))

Median test scores are given below calculated:
43.405
