In [ ]:
# numpy Continuation 

In [6]:
import numpy as np # alias name as np!

In [47]:
array_of_ones=np.ones((3,4)) # 3 rows and 4 columns (x,y) where x is representing rows y is representing columns

In [8]:
array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#how to print array without decimals

In [72]:
array_of_ones_int=np.ones((3,4),dtype=np.int16)
print(array_of_ones_int)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [82]:
array_empty=np.empty((2,3))
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
idenity matrix

In [92]:
array_eye=np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
range function

In [ ]:
range(1,10)---->

In [37]:
#arange

In [ ]:
# requirement is to print the array of even numbers 20

In [39]:
array_of_evens=np.arange(2,20,2)# last num is always exclusive (start value and end value, stepcount)

In [38]:
array_of_evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])